/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package informacionuniversidad;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author KrRD
 */
public class Admisiones extends javax.swing.JFrame {

    /**
     * Creates new form Admisiones
     */
    public Admisiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        txtnumero = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtcarrera = new javax.swing.JTextField();
        txtsemestre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtarchivo = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnabrir = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admisiones ");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("Numero de Identificación:");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Nombres:");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos:");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Carrera:");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Semestre:");

        btnguardar.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });

        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedadKeyTyped(evt);
            }
        });

        txtcarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcarreraKeyTyped(evt);
            }
        });

        txtsemestre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsemestreKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Nombre del Archivo");

        btneliminar.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnabrir.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        btnabrir.setText("Abrir");
        btnabrir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirActionPerformed(evt);
            }
        });

        btnlimpiar.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Ver otros archivos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Archivos disponibles");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator3);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnombres, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtsemestre, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtedad, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtcarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtarchivo)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnabrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

     
        Estudiante std = new Estudiante();
        String nombre_Archivo = txtarchivo.getText();
        
     
     std.numero = Integer.parseInt(txtnumero.getText());
     std.nombres = (txtnombres.getText());
     std.apellidos = (txtapellidos.getText());
     std.edad = Integer.parseInt(txtedad.getText());
     std.carrera = (txtcarrera.getText());
     std.semestre = Integer.parseInt(txtsemestre.getText());
     
     int b = nombre_Archivo.length();
       char c = nombre_Archivo.charAt(b-4);
       char d = nombre_Archivo.charAt(b-3);
       char e = nombre_Archivo.charAt(b-2);
       char g = nombre_Archivo.charAt(b-1);
       String palabra = c+""+d+""+e+""+g;

        if (palabra.equals(".txt"))
        {
          FileWriter fichero = null; 
         
          
          try{
        
        if( !nombre_Archivo.equals("")) {
            
            File archivo = new File(nombre_Archivo);
            
            PrintWriter wrtStudent = new PrintWriter(archivo);

            wrtStudent.println("Número de identificación: "+std.numero);
            wrtStudent.println("Nombres: "+std.nombres);
            wrtStudent.println("Apellidos: "+std.apellidos);
            wrtStudent.println("Edad: "+std.edad);
            wrtStudent.println("Carrera: "+std.carrera);
            wrtStudent.println("Semestre: "+std.semestre);
           
            wrtStudent.close();
           
            JOptionPane.showMessageDialog(this, "\nNúmero de identifiación:  "+ std.numero+
               "\n"+"\tNombres:  "+ std.nombres+"\n"+"\tApellidos:  "+ std.apellidos+"\n"+"\tEdad:  "+std.edad+
               "\n"+"\tCarrera:  "+ std.carrera+"\n"+"\tSemestre:  "+ std.semestre,"Registrado",JOptionPane.INFORMATION_MESSAGE);
         
            }
    
 }
          catch (Exception ex) 
            { 
              JOptionPane.showMessageDialog(this,"El archivo debe terminar en .txt");
            }
            }
        
        this.txtnumero.setText(" ");
        this.txtnombres.setText(" ");
        this.txtapellidos.setText(" ");
        this.txtedad.setText(" ");
        this.txtcarrera.setText(" ");
        this.txtsemestre.setText(" ");
        this.txtarchivo.setText(" ");

        this.txtnumero.grabFocus();
       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        

 try
     {
        String nombre = JOptionPane.showInputDialog("Nombre del archivo a eliminar:");
        File fichero = new File(nombre);
    
        //Comprobamos la existencia del archivo
        if (fichero.exists()){
            fichero.delete();
            JOptionPane.showMessageDialog(null,"Archivo Eliminado");                   
        }else{
            JOptionPane.showMessageDialog(null,"No existe ningun archivo con"
             + "este nombre, recuerde escribir al final del archivo sin "
             + "espacios .txt"); 
        }
     }catch (NullPointerException e){
        // Si llega a dar cancelar al inputdialog, no generar nada 
     }



    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
        
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtnumeroKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        
        char ca = evt.getKeyChar();
        if ((ca < 'a' || ca > 'z') && (ca < 'A' || ca > 'Z')
                && ca != 'á' //Minúsculas            
                && ca != 'é'
                && ca != 'í'
                && ca != 'ó'
                && ca != 'ú'
                && ca != 'Á' //Mayúsculas            
                && ca != 'É'
                && ca != 'Í'
                && ca != 'Ó'
                && ca != 'Ú'
                && (ca != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
       
        char ca = evt.getKeyChar();
        if ((ca<'a'||ca>'z') && (ca < 'A'||ca > 'Z')
                 && ca != 'á' //Minúsculas            
                && ca != 'é'
                && ca != 'í'
                && ca != 'ó'
                && ca != 'ú'
                && ca != 'Á' //Mayúsculas            
                && ca != 'É'
                && ca != 'Í'
                && ca != 'Ó'
                && ca != 'Ú'
                &&(ca!=(char)KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtapellidosKeyTyped
 
    private void btnabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirActionPerformed
        //Guardando el nombre del archivo que desea abrir      
  String nombre = JOptionPane.showInputDialog("Escribe el nombre del archivo:"); 
  File archivo = null;
  FileReader fr = null;
  BufferedReader br = null;
      
    try 
      {
        //Se instancia el archivo
        archivo = new File (nombre);

        //Podemos abrir un fichero de texto para leer usando la clase FileReader.
        fr = new FileReader (archivo); 

        //Se instancia el buffer, para almacenar datos de lectura
        br = new BufferedReader(fr);

        /*Utilizaremos esta variable junto con el while, para leer cada linea
          del archivo*/
        String linea;
        while((linea=br.readLine())!=null)
           {
            JOptionPane.showMessageDialog(null,linea);
           } 
         
         /*En caso tal de que no existe ningun archivo con el nombre, o el 
           nombre este mal escrito*/
       }
    catch (FileNotFoundException ex) 
       {
           // Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(null,"No existe ningun archivo con este"
                  + " nombre, recuerde escribir al final del archivo sin espacios"
                  + " .txt");  
       }
    catch (IOException ex) 
       {
         Logger.getLogger(Admisiones.class.getName()).log(Level.SEVERE, null, ex);
       }
    catch (NullPointerException e)
       {
        // Si llega a dar cancelar al inputdialog, no generar nada
       }
      
    }//GEN-LAST:event_btnabrirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        Archivos file = new Archivos();
        file.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
         try
      {
        String nombre = JOptionPane.showInputDialog("Escribe el nombre del archivo:");
        File fichero = new File(nombre);


        if (fichero.exists())
           {
             fichero.delete();

               try 
                 {
                       File fichero2 = new File(nombre); 
                       PrintWriter archivo_editable = new PrintWriter(fichero2);
                       archivo_editable.close();
                       JOptionPane.showMessageDialog(null,"Archivo Limpio");  

                   //En caso tal de que no exista el archivo, o el nombre sea incorrecto    
                 } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(null,"No existe ningun archivo con este"
                            + " nombre, recuerde escribir al final del archivo sin espacios"
                            + " .txt"); 
                 } catch (NullPointerException e){
                     // Si llega a dar cancelar al inputdialog, no generar nada 
                 } 
           }
           else
           {
               JOptionPane.showMessageDialog(null,"No existe ningun archivo con este"
                         + " nombre, recuerde escribir al final del archivo sin espacios"
                         + " .txt"); 
           }
       }
    catch (NullPointerException e)
       {
              // Si llega a dar cancelar al inputdialog, no generar nada
       }
 
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadKeyTyped
         char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtedadKeyTyped

    private void txtcarreraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarreraKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á' //Minúsculas            
                && car!= 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayúsculas            
                && car != 'É'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcarreraKeyTyped

    private void txtsemestreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsemestreKeyTyped
          char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtsemestreKeyTyped

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       try
    {
      //Se crea la variable con la direccion de la carpeta  
      String directorio = "C:\\Users\\User\\Documents\\NetBeansProjects\\InformacionUniversidad";
      //Se crea el objeto con el contenido de la carpeta
      File carpeta = new File(directorio);
      
       if (carpeta.exists())
         { 
           File[] ficheros = carpeta.listFiles();
           for (int x=0;x<ficheros.length;x++)
            { 
              //Para saber si son los archivos correctos (los .txt= 
                String a = ficheros[x].getName();
                int b = a.length();
                char c = a.charAt(b-4);
                char d = a.charAt(b-3);
                char e = a.charAt(b-2);
                char g = a.charAt(b-1);
                String palabra = c+""+d+""+e+""+g;

                if (palabra.equals(".txt"))
                  {
                   JOptionPane.showMessageDialog(null,ficheros[x].getName());
                  }
             }
          }
       else
          {
           //En caso tal de que la carpeta no existe o fue movida   
           JOptionPane.showMessageDialog(this,"No existe la carpeta o no hay archivos disponibles, "+
                "por favor cambie la dirección ","Archivos",JOptionPane.INFORMATION_MESSAGE);
           }
     }
    catch (StringIndexOutOfBoundsException ex)
     {
       //En caso tal que de cancel en el joptioninput, no genere error
     }

                                     
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admisiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admisiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabrir;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtarchivo;
    private javax.swing.JTextField txtcarrera;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtsemestre;
    // End of variables declaration//GEN-END:variables
}
